<?php
/**
 * Created by PhpStorm.
 * User: POE1
 * Date: 07/12/2018
 * Time: 16:31
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hello':
      $variables = [
        ':toolbar' => Url::fromRoute('help.page', ['name' => 'hello'])
          ->toString(),
        ':automated_cron' => (\Drupal::moduleHandler()
          ->moduleExists('automated_cron')) ? Url::fromRoute('help.page', ['name' => 'automated_cron'])
          ->toString() : '#',
      ];
      
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is just for saying Hello', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= t('This is just for fun so enjoy and have fun :)');
      
      return $output;
  }
}

/**
 * Implements hook_cron().
 */
function hello_cron() {
  // ***** Suppression des log de connexion en fonction du paramètre ***** //
  $purge_days_number = \Drupal::config('hello.settings')->get('purge_days_number');
  
  // Si le paramètre est différent de 0
  if($purge_days_number != 0)
  {
    // On commence par convertir le nombre de jour por la purge en seconde
    $timestamp_pdn = 24*3600*$purge_days_number;
  
    // On enlève le timestamp de purge au timestamp courrant pour obtenir la valeur à comparer en base
    $timestamp_compare = time() - $timestamp_pdn;
  
    // On crée la requete de suppression des données
    $database = \Drupal::database();
    $nb_delete = $database->delete('hello_user_statistics')->condition('time', $timestamp_compare, '<=')->execute();
  
    // On envoi un message pour avertir du nombre d'éléments supprimés
    $messenger = Drupal::messenger();
    $messenger->addMessage(
      t('Connexion log(s) deleted : ' . $nb_delete)
    );
  
    // Ajout du message en recent log
    \Drupal::logger('cron')->info('Connexion log deleted (%nb elements)',
      [
        '%nb' => $nb_delete,
      ]
    );
  }
  // ***** Fin de la partie suppression des logs de connexion ***** //
}

/**
 * Implements hook_user_login().
 */
function hello_user_login(UserInterface $account) {
  $messenger = Drupal::messenger();
  $messenger->addMessage(
    t("Hello %name, hope you're doing fine ?",
      ['%name' => $account->getAccountName()]
    ));
  
  // on commence par regarder si le role du user fait partie des roles traqués
  // récupération de la config
  $config_user_roles = Drupal::config('hello.settings')->get('user_roles');
  // Récupération des roles de l'utilisateur
  $user_roles = $account->getRoles();
  
  // On regarde si il y a au moins une occurence commune dans les tableaux alors on track
  $tab_compare = array_intersect($config_user_roles, $user_roles);
  if(count($tab_compare) > 0){
    // Insertion de l'évenement connexion en base de données
    $insert = [
      'time' => REQUEST_TIME,
      'action' => 1,
      'uid' => $account->id(),
    ];
    // Execution de la requete
    $database = \Drupal::database();
    $database->insert('hello_user_statistics')->fields($insert)->execute();
  }
}

/**
 * Implements hook_user_logout().
 */
function hello_user_logout(AccountInterface $account) {
  // On récupère les roles depuis la configuration
  $config_user_roles = Drupal::config('hello.settings')->get('user_roles');
  // On récupère les roles de l'utilisateur
  $user_roles = $account->getRoles();
  
  // On regarde si il y a des occurences communes dans les deux tableaux de roles alors on track
  $tab_compare = array_intersect($config_user_roles, $user_roles);
  if(count($tab_compare) > 0){
    // Insertion de l'évenement déconnexion en base de données
    $insert = [
      'time' => REQUEST_TIME,
      'action' => 0,
      'uid' => $account->id(),
    ];
  
    $database = \Drupal::database();
    $database->insert('hello_user_statistics')->fields($insert)->execute();
  }
}

function hello_user_delete(UserInterface $account){
  // On efface les occurences concernant le user supprimé dans la base hello_user_statistics
  $database = \Drupal::database();
  $database->delete('hello_user_statistics')->condition('uid', $account->id())->execute();
}

/**
 * Implements hook_theme().
 */
function hello_theme($existing, $type, $theme, $path) {
  return [
    'hello_user_connexion' => [
      'template' => 'hello-user-connexion',
      'variables' => [
        'user' => NULL,
        'nb_connect' => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function hello_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {
  //récupération de la configuration
  $config_user_roles = Drupal::config('hello.settings')->get('user_roles');
  
  // Récupération de l'entity type mnager
  $entity_manager = Drupal::entityTypeManager();
  
  // Récupération des roles utilisateurs
  $roles = $entity_manager->getStorage('user_role')->loadMultiple();
  
  $roles_tab = [];
  foreach($roles as $role){
    if($role->id() != 'anonymous' AND $role->id() != 'authenticated')
    $roles_tab[$role->id()] = $role->label();
  }
  
  $form['activity_collect'] = [
    '#type' => 'details',
    '#title' => t('Role(s) that you want to collect activity'),
    'user_roles' => [
      '#type' => 'checkboxes',
      '#options' => $roles_tab,
      '#default_value' => $config_user_roles,
    ],
    '#weight' => '-100'
  ];
  
  $form['#submit'][] = 'user_admin_settings_alter_submit';
}

function user_admin_settings_alter_submit(&$form, FormStateInterface $form_state){
  // On enregistre la valeur sélectionnée
  Drupal::configFactory()->getEditable('hello.settings')->set('user_roles', $form_state->getValue('user_roles'))->save();
}